version: "3.8"
services:
  web:
    build: app/
    expose:
      - "5000"
    ports:
      - 5000:5000
    env_file:
      - ./.env
    container_name: app_server
    networks:
      - nginx_network

  nginx:
    build: nginx/
    expose:
      - "80"
    networks:
      - nginx_network
    container_name: proxy_server
    depends_on:
      - web

networks:
  nginx_network:
    driver: bridge
  

