version: "3.7"
services:
  web:
    build: app/
    expose:
      - "5000"
    ports:
      - 5000:5000
    env_file:
      - ./.env
    container_name: app_server

  nginx:
    build: nginx/
    ports:
      - 80:80
      - 443:443
    container_name: proxy_server
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
